params:
  epochs: 3
  batch_size: 32 
  no_classes: 10
  loss_functions: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000

artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: plot.png
  
logs:
  logs_dir: logs
  general_logs: general_logs.log
  tensorboard_logs: tensorboard_logs.log